-- MySQL Script generated by MySQL Workbench
-- Mon Jul 15 10:23:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MM
-- -----------------------------------------------------
/*CREATE SCHEMA `db_money_manager` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;*/
-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(10,2) NULL,
  `tema` VARCHAR(100) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_instituicao` ;

CREATE TABLE IF NOT EXISTS `tipo_instituicao` (
  `idtipoinstituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipoinstituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituicao` ;

CREATE TABLE IF NOT EXISTS `instituicao` (
  `idinstituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `idusuario` INT NOT NULL,
  `idtipo` INT NOT NULL,
  PRIMARY KEY (`idinstituicao`),
  INDEX `idusuario_instituicao_idx` (`idusuario` ASC) VISIBLE,
  INDEX `idtipo_instituicao_idx` (`idtipo` ASC) VISIBLE,
  CONSTRAINT `idusuario_instituicao`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipo_instituicao`
    FOREIGN KEY (`idtipo`)
    REFERENCES `tipo_instituicao` (`idtipoinstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quem` ;

CREATE TABLE IF NOT EXISTS `quem` (
  `idquem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `saldo` DECIMAL(10,2) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idquem`),
  INDEX `idusuario_quem_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `idusuario_quem`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_registro` ;

CREATE TABLE IF NOT EXISTS `tipo_registro` (
  `idtiporegistro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtiporegistro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classificacao` ;

CREATE TABLE IF NOT EXISTS `classificacao` (
  `idclassificacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idclassificacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro` ;

CREATE TABLE IF NOT EXISTS `registro` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `data` DATE NOT NULL,
  `momento_registro` TIMESTAMP NULL,
  `idusuario` INT NOT NULL,
  `idquem` INT NOT NULL,
  `idtipo` INT NOT NULL,
  `idclassificacao` INT NOT NULL,
  `idinstituicao` INT NOT NULL,
  PRIMARY KEY (`idregistro`),
  INDEX `idusuario_registro_idx` (`idusuario` ASC) VISIBLE,
  INDEX `idquem_registro_idx` (`idquem` ASC) VISIBLE,
  INDEX `idtipo_registro_idx` (`idtipo` ASC) VISIBLE,
  INDEX `idclassificacao_idx` (`idclassificacao` ASC) VISIBLE,
  INDEX `idinstituicao_registro_idx` (`idinstituicao` ASC) VISIBLE,
  CONSTRAINT `idusuario_registro`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idquem_registro`
    FOREIGN KEY (`idquem`)
    REFERENCES `quem` (`idquem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipo_registro`
    FOREIGN KEY (`idtipo`)
    REFERENCES `tipo_registro` (`idtiporegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idclassificacao_registro`
    FOREIGN KEY (`idclassificacao`)
    REFERENCES `classificacao` (`idclassificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idinstituicao_registro`
    FOREIGN KEY (`idinstituicao`)
    REFERENCES `instituicao` (`idinstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta_mensal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta_mensal` ;

CREATE TABLE IF NOT EXISTS `conta_mensal` (
  `idconta` INT NOT NULL AUTO_INCREMENT,
  `descricao` MEDIUMTEXT NULL,
  `dia_vencimento` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idquem` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`idconta`),
  INDEX `idusuario_conta_idx` (`idusuario` ASC) VISIBLE,
  INDEX `idquem_conta_idx` (`idquem` ASC) VISIBLE,
  CONSTRAINT `idusuario_conta`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idquem_conta`
    FOREIGN KEY (`idquem`)
    REFERENCES `quem` (`idquem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tipo_instituicao`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `tipo_instituicao` (`idtipoinstituicao`, `nome`) VALUES (1, 'Carteira');
INSERT INTO `tipo_instituicao` (`idtipoinstituicao`, `nome`) VALUES (2, 'Banco');
INSERT INTO `tipo_instituicao` (`idtipoinstituicao`, `nome`) VALUES (3, 'Corretora');
INSERT INTO `tipo_instituicao` (`idtipoinstituicao`, `nome`) VALUES (4, 'Empresa');
INSERT INTO `tipo_instituicao` (`idtipoinstituicao`, `nome`) VALUES (5, 'Governamental');
INSERT INTO `tipo_instituicao` (`idtipoinstituicao`, `nome`) VALUES (6, 'Outras');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tipo_registro`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `tipo_registro` (`idtiporegistro`, `nome`) VALUES (1, 'Receita');
INSERT INTO `tipo_registro` (`idtiporegistro`, `nome`) VALUES (2, 'Despesa');
INSERT INTO `tipo_registro` (`idtiporegistro`, `nome`) VALUES (3, 'Está me devendo');
INSERT INTO `tipo_registro` (`idtiporegistro`, `nome`) VALUES (4, 'Estou devendo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `classificacao`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (1, 'Alimentação');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (2, 'Taxas/Impostos');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (3, 'Transporte');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (4, 'Moradia');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (5, 'Saúde');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (6, 'Educação');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (7, 'Lazer');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (8, 'Hobbies');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (9, 'Academia');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (10, 'Beleza');
INSERT INTO `classificacao` (`idclassificacao`, `nome`) VALUES (11, 'Vestuário');

COMMIT;